app = 'zion-dashboard'
primary_region = 'gig'

[env]
  NEXT_PUBLIC_HOST_API = "https://zion-api.fly.dev"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
