import { AppSidebar } from "@/components/sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
    display: "swap",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { sessionId } = await auth();
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

    return (
        <ClerkProvider dynamic={true}>
            <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
                <body className="font-sans antialiased">
                    {sessionId ? (
                        <SidebarProvider defaultOpen={defaultOpen}>
                            <AppSidebar />
                            <main className="w-full">
                                <SiteHeader />
                                <div className="container p-10">{children}</div>
                                <Toaster />
                            </main>
                        </SidebarProvider>
                    ) : (
                        <>{children}</>
                    )}
                </body>
            </html>
        </ClerkProvider>
    );
}
